db_uri = "postgres://postgres@postgres/test"
server_addr = "0.0.0.0:8000"
sled_dir = "/sled"
redis_uri = "redis://redis:6379"
static_dir = "static"
log_level = "debug"
fixed_key = "1234567812345678123456781234567812345678123456781234567812345678"
admin_name = "Schrodinger ZHU"

[cors]
origin = "*"
wildcard = true