version: '2.3'
services:
  # postgres
  postgres:
    image: postgres:14.2
    ports:
    - "5432:5432"
    env_file: env/postgres.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
    - tachyon-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:6.2.6
    ports:
    - "6379:6379"
    volumes:
    - tachyon-redis-data:/data

volumes:
  tachyon-postgres-data:
    driver: local
  tachyon-redis-data:
    driver: local
