version: '2.3'
services:
  # postgres
  postgres:
    image: postgres:14.2
    env_file: env/postgres.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - tachyon-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:6.2.6
    volumes:
      - tachyon-redis-data:/data

  dev:
    build: .
    ports:
      - "8000:8000"
    links:
      - "postgres:postgres"
      - "redis:redis"
    environment:
      - DATABASE_URL=postgres://postgres@postgres/test
    ulimits:
      memlock: -1
    volumes:
      - type: bind
        source: ../
        target: /tachyon
        read_only: true
      - sled-data:/sled
      - build-cache:/tachyon/target
      - node-modules:/tachyon/tachyon-frontend/node_modules
      - cargo-git:/root/.cargo/git
      - cargo-registry:/root/.cargo/registry
      - type: tmpfs
        target: /tachyon/tachyon-frontend/dist
      - type: tmpfs
        target: /tachyon/tachyon-frontend/.tmp

volumes:
  cargo-git:
  cargo-registry:
  node-modules:
  build-cache:
  sled-data:
  tachyon-postgres-data:
    driver: local
  tachyon-redis-data:
    driver: local
