version: '2.3'
services:
  # tachyon: &tachyon
  #   image: 
  #   depends_on:
  #   - postgres
  #   - redis
  #   - redis-cache
  #   env_file: env/tachyon.env
  #   user: 'unit:root'
  #   volumes:

  # postgres
  postgres:
    image: postgres:14.2
    # env_file: env/postgres.env
    volumes:
    - tachyon-postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:6.2.6
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    # env_file: env/redis.env
    volumes:
    - tachyon-redis-data:/data
  redis-cache:
    image: redis:6.2.6
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    # env_file: env/redis-cache.env

volumes:
  tachyon-postgres-data:
    driver: local
  tachyon-redis-data:
    driver: local
