[package]
name = "tachyon-template"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sailfish = "0.4.0"
async-trait = "0.1"
actix-web = { version = "4.0" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
