on: [push]

name: Miri

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nettle
        run: sudo apt-get install -y nettle-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Miri
        run: |
          rustup toolchain install nightly-2022-03-12 --component miri
          rustup override set nightly-2022-03-12
          cargo miri setup
          cargo miri test --release --all-features
