on: [push]

name: Build and Tests

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Toolchain
        run: |    
          rustup toolchain install nightly --profile minimal
          rustup override set nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features

      - name: Miri
        run: |
          rustup toolchain install nightly-2022-03-12 --component miri
          rustup override set nightly-2022-03-12
          cargo miri setup
          cargo miri test --release --all-features
